from numba import njit
import numpy as np
import glm
import math

# voxel ids
FACES = [
    # all 26 possible directions
    ( 0, 1, 0),
    ( 0,-1, 0),
    (-1, 0, 0),
    ( 1, 0, 0),
    ( 0, 0, 1),
    ( 0, 0,-1),
]

# OpenGL settings
MAJOR_VER, MINOR_VER = 3, 3
DEPTH_SIZE = 24
NUM_SAMPLES = 0 # antialiasing

# resolution
WIN_RES = glm.vec2(1920, 1080)

# world generation
SEED = 16

# ray casting
MAX_RAY_DIST = 6

# chunk
CHUNK_SIZE = 48
H_CHUNK_SIZE = CHUNK_SIZE // 2
CHUNK_AREA = CHUNK_SIZE * CHUNK_SIZE
CHUNK_VOL = CHUNK_AREA * CHUNK_SIZE
CHUNK_SPHERE_RADIUS = H_CHUNK_SIZE * math.sqrt(3)

# world
WORLD_W, WORLD_H = 3, 2
WORLD_D = WORLD_W
WORLD_AREA = WORLD_W * WORLD_D
WORLD_VOL = WORLD_AREA * WORLD_H

# world center
CENTER_XZ = WORLD_W * H_CHUNK_SIZE
CENTER_Y = WORLD_H * H_CHUNK_SIZE

# camera
ASPECT_RATIO = WIN_RES.x / WIN_RES.y
FOV_DEG = 70
V_FOV = glm.radians(FOV_DEG)  # vertical FOV
H_FOV = 2 * math.atan(math.tan(V_FOV * 0.5) * ASPECT_RATIO)  # horizontal FOV
NEAR = 0.1
FAR = 2000.0
PITCH_MAX = glm.radians(89)

# player
PLAYER_HEIGHT = 1.8 # int
PLAYER_WIDTH = 0.8 # int

PLAYER_SPEED = 0.005
PLAYER_AIR_SPEED = 0.00001
PLAYER_JUMP_SPEED = 0.003
PLAYER_GRAVITY = 10e-6
PLAYER_ROT_SPEED = 0.003

PLAYER_ACCELERATION = 0.08
PLAYER_AIR_RESISTANCE = 0.99

PLAYER_DAMPING_GROUND = 15
PLAYER_DAMPING_AIR = 2

PLAYER_FRICTION = 0.004

MOUSE_SENSITIVITY = 0.004
DOUBLE_PRESS_TIME_WINDOW = 500

# colors
BG_COLOR = glm.vec3(0.58, 0.83, 0.99)

# textures
SAND = 1
GRASS = 2
DIRT = 3
STONE = 4
SNOW = 5
LEAVES = 6
WOOD = 7
AGT_START = 8
AGT_TARGET = 9
AGT_DEATH = 10
AGT_PENALTY = 11

# terrain levels
SNOW_LVL = 54
STONE_LVL = 49
DIRT_LVL = 40
GRASS_LVL = 8
SAND_LVL = 7

# tree settings
TREE_PROBABILITY = 0.02
TREE_WIDTH, TREE_HEIGHT = 4, 8
TREE_H_WIDTH, TREE_H_HEIGHT = TREE_WIDTH // 2, TREE_HEIGHT // 2
MIN_TREE_HEIGHT = 4
MAX_TREE_HEIGHT = 10


# water
WATER_LINE = 5.6
WATER_AREA = 5 * CHUNK_SIZE * WORLD_W

# cloud
CLOUD_SCALE = 25
CLOUD_HEIGHT = WORLD_H * CHUNK_SIZE * 2

# agent
STREAM_QUALITY = 10
STREAM_ASPECT = 16 * STREAM_QUALITY, 9 * STREAM_QUALITY
AGENT_WALKING_SPEED = 0.005
AGENT_GRAVITY = 10e-6
AGENT_TERMINAL_VELOCITY = 20e-3
AGENT_ROTATION_SPEED = 0.1
AGENT_HEIGHT = 2 # int
AGENT_WIDTH = 0.8 # int
AGENT_JUMP_SPEED = 0.005